-- Migration 013: Add Beacon System tables for C2-like agent management
-- This creates the infrastructure for managing remote beacon agents

-- Beacons table - stores registered beacon agents
CREATE TABLE IF NOT EXISTS beacons (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    beacon_id VARCHAR(64) UNIQUE NOT NULL,  -- Unique identifier generated by beacon
    hostname VARCHAR(255) NOT NULL,
    internal_ip VARCHAR(45),
    external_ip VARCHAR(45),
    os_info VARCHAR(255),
    os_version VARCHAR(100),
    username VARCHAR(255),
    domain VARCHAR(255),
    process_name VARCHAR(255),
    process_id INTEGER,
    architecture VARCHAR(20),  -- x64, x86, arm64
    beacon_version VARCHAR(20),
    
    -- Status tracking
    status VARCHAR(20) DEFAULT 'active',  -- active, dormant, dead, killed
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    first_seen TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    check_in_count INTEGER DEFAULT 0,
    
    -- Configuration
    sleep_interval INTEGER DEFAULT 60,  -- seconds
    jitter_percent INTEGER DEFAULT 10,  -- percentage
    
    -- Metadata
    tags TEXT[],  -- Array of tags for grouping
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Beacon jobs table - job queue for beacons
CREATE TABLE IF NOT EXISTS beacon_jobs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    beacon_id VARCHAR(64) NOT NULL REFERENCES beacons(beacon_id) ON DELETE CASCADE,
    
    -- Job definition
    job_type VARCHAR(50) NOT NULL,  -- domain_scan, vulnerability_scan, powershell, shell
    command TEXT,  -- Command/script to execute
    parameters JSONB DEFAULT '{}',  -- Job parameters (api tokens, config, etc)
    
    -- Status tracking
    status VARCHAR(20) DEFAULT 'pending',  -- pending, sent, running, completed, failed, cancelled
    priority INTEGER DEFAULT 5,  -- 1-10, higher = more urgent
    
    -- Timing
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sent_at TIMESTAMP WITH TIME ZONE,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    
    -- Results
    result_output TEXT,
    result_error TEXT,
    exit_code INTEGER,
    
    -- Metadata
    created_by VARCHAR(255) DEFAULT 'operator',
    notes TEXT
);

-- Beacon job results table - detailed results and artifacts
CREATE TABLE IF NOT EXISTS beacon_job_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id UUID NOT NULL REFERENCES beacon_jobs(id) ON DELETE CASCADE,
    beacon_id VARCHAR(64) NOT NULL REFERENCES beacons(beacon_id) ON DELETE CASCADE,
    
    -- Result data
    output_type VARCHAR(50) DEFAULT 'text',  -- text, json, file, screenshot
    output_data TEXT,
    output_size INTEGER,
    
    -- File artifacts
    file_name VARCHAR(255),
    file_path VARCHAR(500),
    file_hash VARCHAR(64),  -- SHA256
    
    -- Timing
    received_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Beacon activity log - audit trail
CREATE TABLE IF NOT EXISTS beacon_activity_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    beacon_id VARCHAR(64) REFERENCES beacons(beacon_id) ON DELETE SET NULL,
    activity_type VARCHAR(50) NOT NULL,  -- checkin, job_received, job_completed, error, etc
    details JSONB DEFAULT '{}',
    ip_address VARCHAR(45),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Pre-built task templates
CREATE TABLE IF NOT EXISTS beacon_task_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) NOT NULL,
    description TEXT,
    job_type VARCHAR(50) NOT NULL,
    command TEXT,
    parameters JSONB DEFAULT '{}',
    icon VARCHAR(50),  -- emoji or icon name
    is_dangerous BOOLEAN DEFAULT FALSE,  -- requires confirmation
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_beacons_status ON beacons(status);
CREATE INDEX IF NOT EXISTS idx_beacons_last_seen ON beacons(last_seen);
CREATE INDEX IF NOT EXISTS idx_beacons_hostname ON beacons(hostname);
CREATE INDEX IF NOT EXISTS idx_beacons_domain ON beacons(domain);

CREATE INDEX IF NOT EXISTS idx_beacon_jobs_beacon ON beacon_jobs(beacon_id);
CREATE INDEX IF NOT EXISTS idx_beacon_jobs_status ON beacon_jobs(status);
CREATE INDEX IF NOT EXISTS idx_beacon_jobs_created ON beacon_jobs(created_at);
CREATE INDEX IF NOT EXISTS idx_beacon_jobs_pending ON beacon_jobs(beacon_id, status) WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_beacon_results_job ON beacon_job_results(job_id);
CREATE INDEX IF NOT EXISTS idx_beacon_activity_beacon ON beacon_activity_log(beacon_id);
CREATE INDEX IF NOT EXISTS idx_beacon_activity_time ON beacon_activity_log(created_at);

-- Insert default task templates
INSERT INTO beacon_task_templates (name, description, job_type, command, parameters, icon, is_dangerous)
VALUES 
    ('Domain Group Scan', 'Scan Active Directory privileged group memberships', 'domain_scan', NULL, '{"auto_upload": true}', '🔍', false),
    ('Vulnerability Scan', 'Collect vulnerability data from Outpost24', 'vulnerability_scan', NULL, '{"auto_upload": true}', '🛡️', false),
    ('System Info', 'Get detailed system information', 'powershell', 'Get-ComputerInfo | ConvertTo-Json', '{}', '💻', false),
    ('List Processes', 'List running processes', 'powershell', 'Get-Process | Select-Object Name, Id, CPU, WorkingSet64 | ConvertTo-Json', '{}', '📋', false),
    ('Network Connections', 'List active network connections', 'powershell', 'Get-NetTCPConnection | Where-Object State -eq "Established" | ConvertTo-Json', '{}', '🌐', false),
    ('Scheduled Tasks', 'List scheduled tasks', 'powershell', 'Get-ScheduledTask | Select-Object TaskName, State, TaskPath | ConvertTo-Json', '{}', '⏰', false),
    ('Local Users', 'List local user accounts', 'powershell', 'Get-LocalUser | Select-Object Name, Enabled, LastLogon | ConvertTo-Json', '{}', '👤', false),
    ('Installed Software', 'List installed software', 'powershell', 'Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, Publisher | ConvertTo-Json', '{}', '📦', false),
    ('Custom PowerShell', 'Execute custom PowerShell command', 'powershell', '', '{}', '⚡', true),
    ('Shell Command', 'Execute shell command', 'shell', '', '{}', '🖥️', true)
ON CONFLICT DO NOTHING;

-- View for beacon dashboard
CREATE OR REPLACE VIEW v_beacon_dashboard AS
SELECT 
    b.id,
    b.beacon_id,
    b.hostname,
    b.internal_ip,
    b.external_ip,
    b.os_info,
    b.username,
    b.domain,
    b.status,
    b.last_seen,
    b.first_seen,
    b.check_in_count,
    b.sleep_interval,
    b.jitter_percent,
    b.tags,
    b.notes,
    -- Calculate actual status based on last_seen
    CASE 
        WHEN b.status = 'killed' THEN 'killed'
        WHEN b.last_seen > NOW() - INTERVAL '5 minutes' THEN 'active'
        WHEN b.last_seen > NOW() - INTERVAL '30 minutes' THEN 'dormant'
        ELSE 'dead'
    END as computed_status,
    -- Job counts
    (SELECT COUNT(*) FROM beacon_jobs j WHERE j.beacon_id = b.beacon_id AND j.status = 'pending') as pending_jobs,
    (SELECT COUNT(*) FROM beacon_jobs j WHERE j.beacon_id = b.beacon_id AND j.status = 'completed') as completed_jobs,
    (SELECT COUNT(*) FROM beacon_jobs j WHERE j.beacon_id = b.beacon_id AND j.status = 'failed') as failed_jobs,
    -- Last job info
    (SELECT j.completed_at FROM beacon_jobs j WHERE j.beacon_id = b.beacon_id AND j.status = 'completed' ORDER BY j.completed_at DESC LIMIT 1) as last_job_time
FROM beacons b;

-- Function to update beacon status on check-in
CREATE OR REPLACE FUNCTION update_beacon_checkin(
    p_beacon_id VARCHAR(64),
    p_hostname VARCHAR(255),
    p_internal_ip VARCHAR(45),
    p_external_ip VARCHAR(45),
    p_os_info VARCHAR(255),
    p_username VARCHAR(255),
    p_domain VARCHAR(255),
    p_process_name VARCHAR(255) DEFAULT NULL,
    p_process_id INTEGER DEFAULT NULL,
    p_architecture VARCHAR(20) DEFAULT NULL,
    p_beacon_version VARCHAR(20) DEFAULT NULL
) RETURNS UUID AS $$
DECLARE
    v_beacon_uuid UUID;
BEGIN
    INSERT INTO beacons (
        beacon_id, hostname, internal_ip, external_ip, 
        os_info, username, domain, process_name, process_id,
        architecture, beacon_version, last_seen, check_in_count
    ) VALUES (
        p_beacon_id, p_hostname, p_internal_ip, p_external_ip,
        p_os_info, p_username, p_domain, p_process_name, p_process_id,
        p_architecture, p_beacon_version, NOW(), 1
    )
    ON CONFLICT (beacon_id) DO UPDATE SET
        hostname = EXCLUDED.hostname,
        internal_ip = EXCLUDED.internal_ip,
        external_ip = EXCLUDED.external_ip,
        os_info = EXCLUDED.os_info,
        username = EXCLUDED.username,
        domain = EXCLUDED.domain,
        process_name = EXCLUDED.process_name,
        process_id = EXCLUDED.process_id,
        architecture = EXCLUDED.architecture,
        beacon_version = EXCLUDED.beacon_version,
        last_seen = NOW(),
        check_in_count = beacons.check_in_count + 1,
        status = 'active',
        updated_at = NOW()
    RETURNING id INTO v_beacon_uuid;
    
    RETURN v_beacon_uuid;
END;
$$ LANGUAGE plpgsql;

